name: Hello World Workflow

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello, World!"
